.TH "Содержание директории C:/Users/Алия/Desktop/Выполненое тестовое задание Bars Group/TestBars Monitor Db Postgresql" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории C:/Users/Алия/Desktop/Выполненое тестовое задание Bars Group/TestBars Monitor Db Postgresql
.SH SYNOPSIS
.br
.PP
.SS "Директории"

.in +1c
.ti -1c
.RI "директория \fBTestBars\fP"
.br
.in -1c
