.TH "Содержание директории C:/Users/Алия/Desktop/Выполненое тестовое задание Bars Group/TestBars Monitor Db Postgresql/TestBars/WorkSheetsGoogle" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории C:/Users/Алия/Desktop/Выполненое тестовое задание Bars Group/TestBars Monitor Db Postgresql/TestBars/WorkSheetsGoogle
.SH SYNOPSIS
.br
.PP
.SS "Директории"

.in +1c
.ti -1c
.RI "директория \fBManagerSpreasheetGoogle\fP"
.br
.in -1c
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBIManagerSpreasheet\&.cs\fP"
.br
.ti -1c
.RI "файл \fBIServices\&.cs\fP"
.br
.ti -1c
.RI "файл \fBIUserAuthentication\&.cs\fP"
.br
.ti -1c
.RI "файл \fBManagerSpreasheet\&.cs\fP"
.br
.ti -1c
.RI "файл \fBServices\&.cs\fP"
.br
.ti -1c
.RI "файл \fBUserAuthentication\&.cs\fP"
.br
.in -1c
