.TH "Содержание директории C:/Users/Алия/Desktop/Выполненое тестовое задание Bars Group/TestBars Monitor Db Postgresql/TestBars/WorkSheetsGoogle/ManagerSpreasheetGoogle" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории C:/Users/Алия/Desktop/Выполненое тестовое задание Bars Group/TestBars Monitor Db Postgresql/TestBars/WorkSheetsGoogle/ManagerSpreasheetGoogle
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBCreatorSheets\&.cs\fP"
.br
.ti -1c
.RI "файл \fBCreatorSpreasheet\&.cs\fP"
.br
.ti -1c
.RI "файл \fBICreatorSheets\&.cs\fP"
.br
.ti -1c
.RI "файл \fBICreatorSpreasheet\&.cs\fP"
.br
.ti -1c
.RI "файл \fBIScanerSheets\&.cs\fP"
.br
.ti -1c
.RI "файл \fBISearchSpreadsheets\&.cs\fP"
.br
.ti -1c
.RI "файл \fBIWriterSheets\&.cs\fP"
.br
.ti -1c
.RI "файл \fBScanerSheets\&.cs\fP"
.br
.ti -1c
.RI "файл \fBSearchSpreadsheets\&.cs\fP"
.br
.ti -1c
.RI "файл \fBWriterSheets\&.cs\fP"
.br
.in -1c
