.TH "Содержание директории C:/Users/Алия/Desktop/Выполненое тестовое задание Bars Group/TestBars Monitor Db Postgresql/TestBars" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории C:/Users/Алия/Desktop/Выполненое тестовое задание Bars Group/TestBars Monitor Db Postgresql/TestBars
.SH SYNOPSIS
.br
.PP
.SS "Директории"

.in +1c
.ti -1c
.RI "директория \fBbin\fP"
.br
.ti -1c
.RI "директория \fBobj\fP"
.br
.ti -1c
.RI "директория \fBProperties\fP"
.br
.ti -1c
.RI "директория \fBWorkProvider\fP"
.br
.ti -1c
.RI "директория \fBWorkServersPostgreSql\fP"
.br
.ti -1c
.RI "директория \fBWorkSheetsGoogle\fP"
.br
.in -1c
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBConfigurationCastleWindsor\&.cs\fP"
.br
.ti -1c
.RI "файл \fBConverter\&.cs\fP"
.br
.ti -1c
.RI "файл \fBDrives\&.cs\fP"
.br
.ti -1c
.RI "файл \fBIDrives\&.cs\fP"
.br
.ti -1c
.RI "файл \fBIWorkFiles\&.cs\fP"
.br
.ti -1c
.RI "файл \fBProgram\&.cs\fP"
.br
.ti -1c
.RI "файл \fBSqlConfig\&.cs\fP"
.br
.ti -1c
.RI "файл \fBWorkFiles\&.cs\fP"
.br
.in -1c
