.TH "C:/Users/Алия/Desktop/Выполненое тестовое задание Bars Group/TestBars Monitor Db Postgresql/TestBars/WorkServersPostgreSql/ManagerConnectionDb.cs" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Алия/Desktop/Выполненое тестовое задание Bars Group/TestBars Monitor Db Postgresql/TestBars/WorkServersPostgreSql/ManagerConnectionDb.cs
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBTestBars\&.WorkServersPostgreSql\&.ManagerConnectionDb\fP"
.br
.RI "Класс управляющий всеми объектами, которые отвечают за получение данных из серверов\&. "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBTestBars\fP"
.br
.ti -1c
.RI "namespace \fBTestBars\&.WorkServersPostgreSql\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
