.TH "C:/Users/Алия/Desktop/Выполненое тестовое задание Bars Group/TestBars Monitor Db Postgresql/TestBars/bin/Debug/Servers list.txt" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Алия/Desktop/Выполненое тестовое задание Bars Group/TestBars Monitor Db Postgresql/TestBars/bin/Debug/Servers list.txt
.SH SYNOPSIS
.br
.PP
.SS "Переменные"

.in +1c
.ti -1c
.RI "Сервер База данных Размер в ГБ Дата обновления LocalServer1 \fBpostgres\fP"
.br
.ti -1c
.RI "Сервер База данных Размер в ГБ Дата обновления LocalServer1 LocalServer1 \fBTest1\fP"
.br
.ti -1c
.RI "Сервер База данных Размер в ГБ Дата обновления LocalServer1 LocalServer1 LocalServer1 \fBtemplate1\fP"
.br
.ti -1c
.RI "Сервер База данных Размер в ГБ Дата обновления LocalServer1 LocalServer1 LocalServer1 LocalServer1 \fBtemplate0\fP"
.br
.ti -1c
.RI "Сервер База данных Размер в ГБ Дата обновления LocalServer1 LocalServer1 LocalServer1 LocalServer1 \fBC\fP"
.br
.in -1c
.SH "Переменные"
.PP 
.SS "Сервер База данных Размер в ГБ Дата обновления LocalServer1 LocalServer1 LocalServer1 LocalServer1 C"

.SS "Сервер База данных Размер в ГБ Дата обновления LocalServer1 postgres"

.SS "Сервер База данных Размер в ГБ Дата обновления LocalServer1 LocalServer1 LocalServer1 LocalServer1 template0"

.SS "Сервер База данных Размер в ГБ Дата обновления LocalServer1 LocalServer1 LocalServer1 template1"

.SS "Сервер База данных Размер в ГБ Дата обновления LocalServer1 LocalServer1 Test1"

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
