.TH "Drives" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Drives
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBIDrives\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "IList< IList< Object > > \fBGetDriveFreeSize\fP ()"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
