.TH "WriterSheets" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WriterSheets
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBIWriterSheets\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBWriterSheets\fP (\fBIWorkFiles\fP workFiles, \fBIDrives\fP drives)"
.br
.ti -1c
.RI "void \fBWriteSheet\fP (string spreadsheet, IList< \fBIServerObj\fP > servers, SheetsService sheetService)"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
