.TH "IUserAuthentication" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IUserAuthentication \- Интерфейс объекта, который отвечает за аутентификацию пользователя  

.SH SYNOPSIS
.br
.PP
.PP
Производные классы:\fBUserAuthentication\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "UserCredential \fBAuthentication\fP ()"
.br
.RI "Начинает аутентификацию, создает файл с настройками для соединения с google api\&. "
.in -1c
.SH "Подробное описание"
.PP 
Интерфейс объекта, который отвечает за аутентификацию пользователя 


.SH "Методы"
.PP 
.SS "UserCredential Authentication ()"

.PP
Начинает аутентификацию, создает файл с настройками для соединения с google api\&. Если файл соединения создан и настроки scope не изменялись, повторной аутентификации не происходит\&. 
.PP
\fBВозвращает\fP
.RS 4
Возврашает файл с настройками api/
.RE
.PP

.PP
Замещается в \fBUserAuthentication\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
