.TH "IManagerSpreasheet" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IManagerSpreasheet \- Интерфейс объекта управляющего всеми компонентами, которые взаимодействуют с goole table и google disk\&.  

.SH SYNOPSIS
.br
.PP
.PP
Производные классы:\fBManagerSpreasheet\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "void \fBStartWorkSpreasheet\fP (IList< \fBIServerObj\fP > servers)"
.br
.RI "Инициализации всех компонентов и начало их работы\&. "
.in -1c
.SH "Подробное описание"
.PP 
Интерфейс объекта управляющего всеми компонентами, которые взаимодействуют с goole table и google disk\&. 


.SH "Методы"
.PP 
.SS "void StartWorkSpreasheet (IList< \fBIServerObj\fP > servers)"

.PP
Инициализации всех компонентов и начало их работы\&. 
.PP
\fBАргументы\fP
.RS 4
\fIservers\fP Передает список серверов с данными\&.
.RE
.PP

.PP
Замещается в \fBManagerSpreasheet\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
