.TH "TestBars.WorkServersPostgreSql" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestBars.WorkServersPostgreSql
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBDbObj\fP"
.br
.RI "Класс для хранения данных из DB\&. "
.ti -1c
.RI "interface \fBIDbObj\fP"
.br
.RI "Интерфейс для взаимодействия с обьектом, который хранит в себе данные из Db\&. "
.ti -1c
.RI "interface \fBIManagerConnectionDb\fP"
.br
.RI "Интерфейс объекта, который управляет всеми компонентами, отвечающими за получение данных из серверов\&. "
.ti -1c
.RI "interface \fBIParseConfiguration\fP"
.br
.RI "Интерфейс объекта, который сканирует и собирает настройки серверов из файла App\&.config\&. "
.ti -1c
.RI "interface \fBIServerObj\fP"
.br
.RI "Интерфейс взаимодействия с объектом, который хранит в себе данные сервера и список \fBIDbObj\fP\&. "
.ti -1c
.RI "interface \fBIWriterServers\fP"
.br
.RI "Интерфейс объекта, который сортирует данные полученные из DB, по объектам для хранения\&. "
.ti -1c
.RI "class \fBManagerConnectionDb\fP"
.br
.RI "Класс управляющий всеми объектами, которые отвечают за получение данных из серверов\&. "
.ti -1c
.RI "class \fBParseConfiguration\fP"
.br
.RI "Класс ,который сканирует и собирает настройки серверов из файла App\&.config\&. "
.ti -1c
.RI "class \fBServerObj\fP"
.br
.RI "Объект, который хранит в себе данные сервера и список DB\&. "
.ti -1c
.RI "class \fBWriterServers\fP"
.br
.RI "Класс сортирует данные полученные из DB, по объектам для хранения\&. "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
