.TH "IWorkFiles" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IWorkFiles
.SH SYNOPSIS
.br
.PP
.PP
Производные классы:\fBWorkFiles\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "void \fBWriteFileTxt\fP (IList< \fBIServerObj\fP > servers)"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
