.TH "IUserAuthentication" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IUserAuthentication
.SH SYNOPSIS
.br
.PP
.PP
Производные классы:\fBUserAuthentication\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "UserCredential \fBAuthentication\fP ()"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
