.TH "Services" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Services
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBIServices\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBServices\fP (\fBIUserAuthentication\fP userAuthentication)"
.br
.ti -1c
.RI "SheetsService \fBGetSheetsService\fP ()"
.br
.ti -1c
.RI "DriveService \fBGetDriveService\fP ()"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
