.TH "SearchSpreadsheets" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SearchSpreadsheets
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBISearchSpreadsheets\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBSearchSpreadsheets\fP (\fBIWorkFiles\fP workFiles)"
.br
.ti -1c
.RI "string \fBSearch\fP (IList< \fBIServerObj\fP > servers, DriveService driveService)"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
