.TH "ManagerSpreasheet" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ManagerSpreasheet
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBIManagerSpreasheet\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBManagerSpreasheet\fP (\fBIServices\fP services, \fBISearchSpreadsheets\fP searchSpreadsheets, \fBICreatorSpreasheet\fP creatorSpreasheet, \fBIScanerSheets\fP scanerSheets)"
.br
.ti -1c
.RI "void \fBStartWorkSpreasheet\fP (IList< \fBIServerObj\fP > servers)"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
