.TH "WorkFiles" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WorkFiles
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBIWorkFiles\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBWorkFiles\fP (\fBIDrives\fP drives)"
.br
.ti -1c
.RI "string \fBSortString\fP (IList< string > liststring)"
.br
.ti -1c
.RI "string \fBCreatestring\fP (IList< \fBIServerObj\fP > servers)"
.br
.ti -1c
.RI "void \fBWriteFileTxt\fP (IList< \fBIServerObj\fP > servers)"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
