.TH "ConfigurationCastleWindsor" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigurationCastleWindsor
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:IWindsorInstaller\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "void \fBInstall\fP (IWindsorContainer container, IConfigurationStore store)"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
