.TH "IServices" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IServices
.SH SYNOPSIS
.br
.PP
.PP
Производные классы:\fBServices\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "SheetsService \fBGetSheetsService\fP ()"
.br
.ti -1c
.RI "DriveService \fBGetDriveService\fP ()"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
