.TH "Drives" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Drives \- Класс, который отвечает за получения списка жестких дисков и размер свободного места на них\&.  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBIDrives\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "IList< IList< Object > > \fBGetDriveFreeSize\fP ()"
.br
.RI "Начинает поиск жестких дисков, заполняет результат в список\&. "
.in -1c
.SH "Подробное описание"
.PP 
Класс, который отвечает за получения списка жестких дисков и размер свободного места на них\&. 


.SH "Методы"
.PP 
.SS "IList<IList<Object> > GetDriveFreeSize ()"

.PP
Начинает поиск жестких дисков, заполняет результат в список\&. 
.PP
\fBВозвращает\fP
.RS 4
Список названий жестких дисков, размер свободного места на них, дата заполнения данных\&.
.RE
.PP

.PP
Замещает \fBIDrives\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
