.TH "Converter" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Converter \- Класс, который преобразует килобайты в гигабайты\&.  

.SH SYNOPSIS
.br
.PP
.SS "Открытые статические члены"

.in +1c
.ti -1c
.RI "static string \fBCalculateBytetoGB\fP (double bytes)"
.br
.RI "Преобразует килобайты в гигабайты\&. "
.in -1c
.SH "Подробное описание"
.PP 
Класс, который преобразует килобайты в гигабайты\&. 


.SH "Методы"
.PP 
.SS "static string CalculateBytetoGB (double bytes)\fC [static]\fP"

.PP
Преобразует килобайты в гигабайты\&. 
.PP
\fBАргументы\fP
.RS 4
\fIbytes\fP предает килобайты
.RE
.PP
\fBВозвращает\fP
.RS 4
Строку с преобразованным числом в гигабайты\&.
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
