.TH "IManagerConnectionDb" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IManagerConnectionDb \- Интерфейс менеджера управляющего всеми объектами, которые отвечают за получение данных из серверов\&.  

.SH SYNOPSIS
.br
.PP
.PP
Производные классы:\fBManagerConnectionDb\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "IList< \fBIServerObj\fP > \fBGetServers\fP ()"
.br
.RI "Метод для возвращения списока серверов и с списками DB\&. "
.in -1c
.SH "Подробное описание"
.PP 
Интерфейс менеджера управляющего всеми объектами, которые отвечают за получение данных из серверов\&. 


.SH "Методы"
.PP 
.SS "IList<\fBIServerObj\fP> GetServers ()"

.PP
Метод для возвращения списока серверов и с списками DB\&. 
.PP
\fBВозвращает\fP
.RS 4
Списки серверов с списками DB\&.Список
.RE
.PP

.PP
Замещается в \fBManagerConnectionDb\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
