.TH "IWriterSheets" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IWriterSheets
.SH SYNOPSIS
.br
.PP
.PP
Производные классы:\fBWriterSheets\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "void \fBWriteSheet\fP (string spreadsheet, IList< \fBIServerObj\fP > servers, SheetsService sheetService)"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
