.TH "TestBars" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestBars
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBConfigurationCastleWindsor\fP"
.br
.ti -1c
.RI "class \fBConverter\fP"
.br
.RI "Класс, который преобразует килобайты в гигабайты\&. "
.ti -1c
.RI "class \fBDrives\fP"
.br
.RI "Класс, который отвечает за получения списка названий жестких дисков и размер свободного места на них\&. "
.ti -1c
.RI "interface \fBIDrives\fP"
.br
.RI "Интерфейс объекта, который отвечает за получения списка названий жестких дисков и размер свободного места на них\&. "
.ti -1c
.RI "interface \fBIWorkFiles\fP"
.br
.RI "Интерфейс объекта, который отвечает за запись данных в txt файл\&. "
.ti -1c
.RI "class \fBProgram\fP"
.br
.ti -1c
.RI "class \fBSqlConfig\fP"
.br
.RI "Класс содержит строку с sql запросом\&. "
.ti -1c
.RI "class \fBWorkFiles\fP"
.br
.RI "Класс, который отвечает за запись данных в txt файл\&. "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
