.TH "TestBars.WorkSheetsGoogle.ManagerSpreasheetGoogle" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestBars.WorkSheetsGoogle.ManagerSpreasheetGoogle
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBCreatorSheets\fP"
.br
.RI "Класс, который создает google лист, в существующей google таблице\&. "
.ti -1c
.RI "class \fBCreatorSpreasheet\fP"
.br
.RI "Класс, который создает google таблицу\&. "
.ti -1c
.RI "interface \fBICreatorSheets\fP"
.br
.RI "Интерфейс объекта, который создает google лист, в существующей google таблице\&. "
.ti -1c
.RI "interface \fBICreatorSpreasheet\fP"
.br
.RI "Интерфейс объекта, который создает google таблицу\&. "
.ti -1c
.RI "interface \fBIScanerSheets\fP"
.br
.RI "Интерфейс объекта, который сканирует таблицу, на наличие листов для каждого сервера\&. "
.ti -1c
.RI "interface \fBISearchSpreadsheets\fP"
.br
.RI "Интерфейс объекта, который ищет таблицы в google disk, по названию\&. "
.ti -1c
.RI "interface \fBIWriterSheets\fP"
.br
.RI "Интерфейс объекта, который отвечает за запись данных в google лист\&. "
.ti -1c
.RI "class \fBScanerSheets\fP"
.br
.RI "Класс, который сканирует таблицу, на наличие листов для каждого сервера\&. "
.ti -1c
.RI "class \fBSearchSpreadsheets\fP"
.br
.RI "Класс, который ищет таблицы в google disk, по названию\&. "
.ti -1c
.RI "class \fBWriterSheets\fP"
.br
.RI "Класс, который отвечает за запись данных в google лист\&. "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
