.TH "DbObj" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DbObj \- Класс для хранения данных из DB\&.  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBIDbObj\fP\&.
.SS "Свойства"

.in +1c
.ti -1c
.RI "string \fBname\fP\fC [get, set]\fP"
.br
.RI "Содержит название DB\&."
.ti -1c
.RI "string \fBsize\fP\fC [get, set]\fP"
.br
.RI "Содержит размер DB, в гигабайтах\&."
.ti -1c
.RI "string \fBupdateDate\fP\fC [get, set]\fP"
.br
.RI "Содержит дату получения данных из DB\&."
.in -1c
.SH "Подробное описание"
.PP 
Класс для хранения данных из DB\&. 



.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
