.TH "IScanerSheets" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IScanerSheets \- Интерфейс объекта, который сканирует таблицу, на наличие листов для каждого сервера\&.  

.SH SYNOPSIS
.br
.PP
.PP
Производные классы:\fBScanerSheets\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "void \fBScanSheets\fP (string ListId, IList< \fBIServerObj\fP > servers, SheetsService sheetService)"
.br
.RI "Сканирует листы в существующей таблице\&. "
.in -1c
.SH "Подробное описание"
.PP 
Интерфейс объекта, который сканирует таблицу, на наличие листов для каждого сервера\&. 


.SH "Методы"
.PP 
.SS "void ScanSheets (string ListId, IList< \fBIServerObj\fP > servers, SheetsService sheetService)"

.PP
Сканирует листы в существующей таблице\&. Eсли лист не найден, вызывается метод объекта: \fBICreatorSheets\fP
.PP
Eсли лист найден, вызывается метод объекта: \fBIWriterSheets\fP и данные у листа обновляются\&.
.PP
\fBАргументы\fP
.RS 4
\fIListId\fP Передает Id google таблицы\&.
.br
\fIservers\fP Передает список серверов с данными\&.
.br
\fIsheetService\fP Передает сервис для взаимодействия с таблицами google\&.
.RE
.PP

.PP
Замещается в \fBScanerSheets\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
