.TH "UserAuthentication" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserAuthentication \- Класс, который отвечает за аутентификацию пользователя\&.  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBIUserAuthentication\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "UserCredential \fBAuthentication\fP ()"
.br
.RI "Начинает аутентификацию, создает файл с настройками для соединения с google api\&. "
.in -1c
.SH "Подробное описание"
.PP 
Класс, который отвечает за аутентификацию пользователя\&. 


.SH "Методы"
.PP 
.SS "UserCredential Authentication ()"

.PP
Начинает аутентификацию, создает файл с настройками для соединения с google api\&. Если файл соединения создан и настроки scope не изменялись, повторной аутентификации не происходит\&. 
.PP
\fBВозвращает\fP
.RS 4
Возврашает файл с настройками api/
.RE
.PP

.PP
Замещает \fBIUserAuthentication\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
