.TH "IServices" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IServices \- Интерфейс объекта, который отвечает, за получение сервисов после аутентификации пользователя\&.  

.SH SYNOPSIS
.br
.PP
.PP
Производные классы:\fBServices\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "SheetsService \fBGetSheetsService\fP ()"
.br
.RI "Инициализирует сервис для работы с google таблицами\&. "
.ti -1c
.RI "DriveService \fBGetDriveService\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
Интерфейс объекта, который отвечает, за получение сервисов после аутентификации пользователя\&. 


.SH "Методы"
.PP 
.SS "DriveService GetDriveService ()"

.PP
Инициализирует сервис для работы с google disk\&.
.PP
\fBВозвращает\fP
.RS 4
Возвращает сервис для работы с google disk\&.
.RE
.PP

.PP
Замещается в \fBServices\fP\&.
.SS "SheetsService GetSheetsService ()"

.PP
Инициализирует сервис для работы с google таблицами\&. 
.PP
\fBВозвращает\fP
.RS 4
Возвращает сервис для google таблиц\&.
.RE
.PP

.PP
Замещается в \fBServices\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
