.TH "ServerObj" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServerObj \- Объект, который хранит в себе данные сервера и список DB\&.  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBIServerObj\fP\&.
.SS "Свойства"

.in +1c
.ti -1c
.RI "string \fBNameServer\fP\fC [get, set]\fP"
.br
.RI "Содержит название сервера\&."
.ti -1c
.RI "IList< \fBIDbObj\fP > \fBDataBases\fP\fC [get, set]\fP"
.br
.RI "Содержит список Db\&."
.in -1c
.SH "Подробное описание"
.PP 
Объект, который хранит в себе данные сервера и список DB\&. 



.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
