.TH "Program" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Program
.SH SYNOPSIS
.br
.PP
.SS "Открытые статические члены"

.in +1c
.ti -1c
.RI "static void \fBStartProgram\fP (object state)"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
