.TH "C:/Users/Алия/Desktop/Выполненое тестовое задание Bars Group/TestBars Monitor Db Postgresql/TestBars/WorkSheetsGoogle/UserAuthentication.cs" 3 "Пн 6 Апр 2020" "TestBars" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Алия/Desktop/Выполненое тестовое задание Bars Group/TestBars Monitor Db Postgresql/TestBars/WorkSheetsGoogle/UserAuthentication.cs
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBTestBars\&.WorkSheetsGoogle\&.UserAuthentication\fP"
.br
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBTestBars\fP"
.br
.ti -1c
.RI "namespace \fBTestBars\&.WorkSheetsGoogle\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для TestBars из исходного текста\&.
